### ISSUE TITLE
Calendar shows January 2015 instead of January 2016

### ISSUE THREAD

**Issue by bixbarton** [concurlabs/CXDurationPicker#23]
This issue does not occur in simulator, only on device.

Running on my iPhone 5, if I scroll down to December 2015 and keep scrolling down, the next month appears as January 2015.

Tested 0.9.0 on device, still present
#12 re-opened

**Comment by bixbarton** [comment]
We have just discovered, this only happens when the region is set to United Kingdom. If the region is set to United States you will not see this. This may also explain why it only happens on device, as our devices are set to UK, but our simulators are set to US.

So if you set your simulator to UK you should be able to recreate the issue.

**Comment by rapuckett** [comment]
Fixed in e1c6cbc00b7ca3ef1c6f0bf54566949fd1f35822

**Comment by pjandak** [comment]
hi Richard , I still see an issue while UK region is selected
